# Generated by Django 4.1.2 on 2022-11-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_postdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetail',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='board.post'),
        ),
    ]
