# Generated by Django 4.1.2 on 2022-11-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_postdetail_post'),
    ]

    operations = [

    ]
