# Generated by Django 4.1.2 on 2022-11-25 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_postdetail_post'),
    ]

    operations = [

    ]
